Has been modified profile screen with components
BC-NOV-20-Proyectos/alerta-covid-mobile-nov20-rn-team-03 pull request #12
Opened 2021-04-13 19:47 UTC by JacintoOrtiz15745

# Description
What did you implemented/Why did you implemented this:
 - I've made the profile screen with reusable components
  
 Example:
  - I've added components by the profile screen 
  
  ## Screenshots 
![Screenshot_1618343156](https://user-images.githubusercontent.com/47754385/114611977-2dddb080-9c67-11eb-8970-2f2b621f4030.png)

![Screenshot_1618343156](https://user-images.githubusercontent.com/47754385/114611733-f7079a80-9c66-11eb-8680-d424e65220a2.png)

2021-04-13 19:54 UTC, fernandoamz requested changes

2021-04-13 19:54 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/Profile/Background.js
> +    <ImageBackground source={require('../../../assets/images/ProfileBackground.png')}></ImageBackground>
Refactor this line

2021-04-13 19:56 UTC, JacintoOrtiz15745 commented on AlertCovidApp/src/components/atoms/Profile/Background.js
> +    <ImageBackground source={require('../../../assets/images/ProfileBackground.png')}></ImageBackground>
How?

2021-04-13 20:06 UTC, JacintoOrtiz15745 commented on AlertCovidApp/src/components/atoms/Profile/Background.js
> +    <ImageBackground source={require('../../../assets/images/ProfileBackground.png')}></ImageBackground>
Done

2021-04-14 15:30 UTC, fernandoamz approved these changes

2021-04-14 15:44 UTC, jjcr11 approved these changes

2021-04-14 15:44 UTC, mariam-rivera approved these changes

2021-04-14 15:46 UTC, merged