Feature#1/UI designs app screens
BC-NOV-20-Proyectos/alerta-covid-mobile-nov20-rn-team-03 pull request #2
Opened 2021-03-20 02:39 UTC by ChantalRamirez

# Description
UI design of all screen
 

https://user-images.githubusercontent.com/58367346/111856805-e297e280-88f2-11eb-8239-848ae881b6c0.mp4

2021-03-22 16:25 UTC, vmagana3 approved these changes, later dismissed
Good work!!

2021-03-22 16:28 UTC, GracielaJazmin submitted a review, later dismissed

2021-03-22 16:47 UTC, fernandoamz requested changes
You need add a blank line at the end of every file

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/Button.js
> +    style={[styles.ButtonWellBad, {backgroundColor: textButton === 'WELL' ? colors.green : colors.orange},]}
Try to do this line easier to read

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/ButtonLarge.js
> +    onPress={ () => navigation.navigate(RouteGo)
Review the identation

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/Form.js
> +        <Text style={{color:'#888888'}}>{TextInput}</Text>
All the colors should be in a constants file

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/ScrollWhite.js
> +        <FormLine Label={'Date'} TextInput={'10/03/2021'}></FormLine>
Why this value is hardcoded?

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/ScrollWhite.js
> +      <FormLine Label={'Symptoms on the day of test'} TextInput={'Yes'}></FormLine>
The same case

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/HistoryTest/History.js
> +        <Text style={{color:'#888888'}}>Viral Test</Text>
Text and styles should be in a constant file. The styles should be inside styles tag

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/HistoryTest/History.js
> +          marginTop: 5,
same case

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/HistoryTest/History2.js
> +export default HistoryData;
New line here

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/Home/BackgroundImage.js
> +     <ImageBackground style={styles.ImageBackground} source={require('../../../assets/images/Welcome.png')}></ImageBackground>
import the image route

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/Symptoms/MultiSelect.js
> +
only should be one line

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/navigations/AppNavigation.js
> +// import { NavigationContainer } from '@react-navigation/native';
can you remove this line?

2021-03-22 16:47 UTC, fernandoamz commented on AlertCovidApp/src/screens/ScanQr.js
> +export default TestResults;
new line

2021-03-22 18:12 UTC, JacintoOrtiz15745 commented on AlertCovidApp/src/components/atoms/GeneralApp/ScrollWhite.js
> +        <FormLine Label={'Date'} TextInput={'10/03/2021'}></FormLine>
What's mean hardcoded?

2021-03-22 18:24 UTC, LeyaimMagma requested changes

2021-03-22 18:24 UTC, LeyaimMagma commented on AlertCovidApp/src/components/atoms/GeneralApp/Form.js
> +export default FormLine;
add blank space

2021-03-22 18:24 UTC, LeyaimMagma commented on AlertCovidApp/src/components/atoms/GeneralApp/ScrollWhite.js
> +        }}>
move to stylessheet

2021-03-22 18:24 UTC, LeyaimMagma commented on AlertCovidApp/src/components/atoms/GeneralApp/ScrollWhite.js
> +export default ScrollWhite;
always end the files with a blank space

2021-03-24 18:23 UTC, vmagana3 submitted a review, later dismissed
Good work!!

2021-03-24 18:33 UTC, fernandoamz requested changes

2021-03-24 18:33 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/BackgroundImage.js
> +        source={require('../../assets/images/Welcome.png')}></ImageBackground>
Add the import for this image.

2021-03-24 18:33 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/GeneralApp/Button.js
> +        {backgroundColor: textButton === 'WELL' ? colors.green : colors.orange},
make this line easier to read

2021-03-24 18:33 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/HistoryTest/History.js
> +            <Text style={{fontSize: 10, color: colors.gray}}>Test failed</Text>
All texts should be in a constants file

2021-03-24 18:33 UTC, fernandoamz commented on AlertCovidApp/src/components/atoms/Profile/UserDataScroll.js
> +      </View>
Did you try using a TextInput?

2021-03-24 18:33 UTC, fernandoamz commented on AlertCovidApp/src/screens/HistorySymptoms.js
> +      <History2 navigation={navigation} />
Change the name of this variable, Review the good practices to name a variable

2021-03-24 23:47 UTC, ChantalRamirez commented on AlertCovidApp/src/components/atoms/BackgroundImage.js
> +        source={require('../../assets/images/Welcome.png')}></ImageBackground>
ok

2021-03-25 15:55 UTC, ChantalRamirez commented on AlertCovidApp/src/components/atoms/GeneralApp/Button.js
> +        {backgroundColor: textButton === 'WELL' ? colors.green : colors.orange},
What do you mean "Make easier" ?? sorry

2021-03-25 16:01 UTC, ChantalRamirez commented on AlertCovidApp/src/components/atoms/GeneralApp/Button.js
> +        {backgroundColor: textButton === 'WELL' ? colors.green : colors.orange},
We use prettier, but we don´t  understand

2021-03-25 20:55 UTC, LeyaimMagma requested changes

2021-03-25 20:55 UTC, LeyaimMagma commented on AlertCovidApp/src/utils/Constants/History.js
> +};
add blank space at the end

2021-03-25 20:55 UTC, LeyaimMagma commented on AlertCovidApp/src/utils/Constants/HistoryConstants.js
> +};
add blank space at the end

2021-03-25 21:25 UTC, fernandoamz approved these changes, later dismissed

2021-03-26 15:33 UTC, Joaquin-Niembro approved these changes

2021-03-26 16:19 UTC, jjcr11 approved these changes

2021-03-26 17:49 UTC, fernandoamz approved these changes

2021-03-29 16:29 UTC, merged